# HuggingFace Dataset File 2
Testing using the datasets library to merge data, specifically the Farsight dataset, and the Tingchih dataset

In [1]:
from datasets import load_dataset
from dotenv import load_dotenv
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

load_dotenv()
n_rows = 3000

c:\Users\User\coding\Lai\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset_facts = load_dataset("Farsight-AI/10k-fact-check-finetune", split="train", streaming=True)
subset_facts = dataset_facts.take(n_rows)
facts_df = pd.DataFrame(list(subset_facts))

dataset_news = load_dataset("tingchih/Multi_News_fact_checking_claims", split="train", streaming=True)
subset_news = dataset_news.take(n_rows)
news_facts_df = pd.DataFrame(list(subset_news))

In [3]:
facts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936 entries, 0 to 1935
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cik                1936 non-null   int64
 1   context            1936 non-null   object
 2   filingDate         1936 non-null   datetime64[ns]
 3   docID              1936 non-null   object
 4   generatedQuestion  1936 non-null   object
 5   answer             1936 non-null   object
 6   model              1936 non-null   object
 7   label              1936 non-null   bool
dtypes: bool(1), datetime64[ns](1), int64(1), object(5)
memory usage: 107.9+ KB

In [4]:
facts_df['label'].value_counts()

label
True     968
False    968
Name: count, dtype: int64

In [5]:
news_facts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Documents  3000 non-null   object
 1   Claim      3000 non-null   object
 2   label      3000 non-null   object
dtypes: object(3)
memory usage: 70.4+ KB

In [6]:
news_facts_df['label'].value_counts()

label
Entailment       1004
Neutral          1002
Contradiction     994
Name: count, dtype: int64

In [7]:
news_facts_df.replace(['Entailment', 'Neutral', 'Contradiction'], ['True', 'Nuanced', 'False'], inplace=True)

In [8]:
facts_df.head()

,cik,context,filingDate,docID,generatedQuestion,answer,model,label
0,3499,Vornado is also entitled to a development fee ...,2017-02-13,0000003499_10-K_2016,What fees does Vornado charge for development ...,The fees Vornado charges for development servi...,gpt-3.5-turbo,True
1,3499,Vornado is also entitled to a development fee ...,2017-02-13,0000003499_10-K_2016,What fees does Vornado charge for development ...,Vornado charges a flat development fee of 6% f...,gpt-3.5-turbo,False
2,3499,The Company has concluded that the large major...,2004-03-02,0000003499_10-K_2003,What challenges and uncertainties does the com...,The passage states that while the company is p...,gpt-3.5-turbo,True
3,3499,The Company has concluded that the large major...,2004-03-02,0000003499_10-K_2003,What challenges and uncertainties does the com...,The company is confident in its ability to suc...,gpt-3.5-turbo,False
4,6207,The plan provides for Company contributions of...,1994-07-29,0000006207_10-K_1994,What is the percentage and maximum amount of C...,The plan provides for Company contributions of...,gpt-3.5-turbo,True

In [9]:
news_facts_df.head()

,Documents,Claim,label
0,"[National Archives Yes, it’s that time again,...",The unemployment rate declined to 8.2% last mo...,True
1,"[National Archives Yes, it’s that time again,...","The economy added 120,000 jobs, compared to 20...",True
2,"[National Archives Yes, it’s that time again,...",The unemployment rate had been expected to hol...,True
3,"[National Archives Yes, it’s that time again,...",The dip in the unemployment rate is due to mor...,True
4,"[National Archives Yes, it’s that time again,...",The dip in the unemployment rate was caused by...,True

In [10]:
news_facts_df['Documents'] = news_facts_df['Documents'].astype("string")
news_facts_df['Documents'] = news_facts_df['Documents'].str.replace('[', '')
news_facts_df['Documents'] = news_facts_df['Documents'].str.replace(']', '')
news_facts_df['Documents'] = news_facts_df['Documents'].str.replace("'", '')
news_facts_df['Documents'].iloc[0]

'National Archives  Yes, it’s that time again, folks. It’s the first Friday of the month, when for one ever-so-brief moment the interests of Wall Street, Washington and Main Street are all aligned on one thing: Jobs.  A fresh update on the U.S. employment situation for January hits the wires at 8:30 a.m. New York time offering one of the most important snapshots on how the economy fared during the previous month. Expectations are for 203,000 new jobs to be created, according to economists polled by Dow Jones Newswires, compared to 227,000 jobs added in February. The unemployment rate is expected to hold steady at 8.3%.  Here at MarketBeat HQ, we’ll be offering color commentary before and after the data crosses the wires. Feel free to weigh-in yourself, via the comments section. And while you’re here, why don’t you sign up to follow us on Twitter.  Enjoy the show. ,  Employers pulled back sharply on hiring last month, a reminder that the U.S. economy may not be growing fast enough to sustain robust job growth. The unemployment rate dipped, but mostly because more Americans stopped looking for work.  The Labor Department says the economy added 120,000 jobs in March, down from more than 200,000 in each of the previous three months.  The unemployment rate fell to 8.2 percent, the lowest since January 2009. The rate dropped because fewer people searched for jobs. The official unemployment tally only includes those seeking work.  The economy has added 858,000 jobs since December _ the best four months of hiring in two years. But Federal Reserve Chairman Ben Bernanke has cautioned that the current hiring pace is unlikely to continue without more consumer spending.'

In [11]:
news_facts_df.head()

,Documents,Claim,label
0,"National Archives Yes, it’s that time again, ...",The unemployment rate declined to 8.2% last mo...,True
1,"National Archives Yes, it’s that time again, ...","The economy added 120,000 jobs, compared to 20...",True
2,"National Archives Yes, it’s that time again, ...",The unemployment rate had been expected to hol...,True
3,"National Archives Yes, it’s that time again, ...",The dip in the unemployment rate is due to mor...,True
4,"National Archives Yes, it’s that time again, ...",The dip in the unemployment rate was caused by...,True

In [12]:
select_facts_df = facts_df[['context', 'answer', 'label']]
select_facts_df.columns = ['documents', 'claim', 'label']
news_facts_df.columns = ['documents', 'claim', 'label']

In [13]:
select_facts_df.head()

,documents,claim,label
0,Vornado is also entitled to a development fee ...,The fees Vornado charges for development servi...,True
1,Vornado is also entitled to a development fee ...,Vornado charges a flat development fee of 6% f...,False
2,The Company has concluded that the large major...,The passage states that while the company is p...,True
3,The Company has concluded that the large major...,The company is confident in its ability to suc...,False
4,The plan provides for Company contributions of...,The plan provides for Company contributions of...,True

In [14]:
claims_df = pd.concat([select_facts_df, news_facts_df])
claims_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4936 entries, 0 to 2999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   documents  4936 non-null   object
 1   claim      4936 non-null   object
 2   label      4936 non-null   object
dtypes: object(3)
memory usage: 154.2+ KB

In [15]:
claims_df.head()

,documents,claim,label
0,Vornado is also entitled to a development fee ...,The fees Vornado charges for development servi...,True
1,Vornado is also entitled to a development fee ...,Vornado charges a flat development fee of 6% f...,False
2,The Company has concluded that the large major...,The passage states that while the company is p...,True
3,The Company has concluded that the large major...,The company is confident in its ability to suc...,False
4,The plan provides for Company contributions of...,The plan provides for Company contributions of...,True

In [16]:
claims_df.tail()

,documents,claim,label
2995,Katy Perry is all about breaking conventional ...,"Charles started using makeup only a year ago, ...",Nuanced
2996,Katy Perry is all about breaking conventional ...,CoverGirl wants to work with role models and b...,Nuanced
2997,Katy Perry is all about breaking conventional ...,Charles is an inspiration for CoverGirl,Nuanced
2998,Katy Perry is all about breaking conventional ...,Teen Vogue agrees that anyone on the gender sp...,Nuanced
2999,Katy Perry is all about breaking conventional ...,E!Online supports Charles' position as a role ...,Nuanced

Merging these datasets can provide useful results, since they are malleable, and can be used to create a larger dataset for training a model.

## Respit dataset work

In [18]:
dataset_repslit = load_dataset("jpd459/resplit_multi_fact_checking_dataset_resampling", split="train", streaming=True)
subset_resplit = dataset_repslit.take(4000) # the dataset has 3.3k rows
resplit_df = pd.DataFrame(list(subset_resplit))
print(resplit_df.info())
resplit_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3394 entries, 0 to 3393
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   claim            3394 non-null   object
 1   evidence         3394 non-null   object
 2   evidence_stance  3394 non-null   object
dtypes: object(3)
memory usage: 79.7+ KB
None

,claim,evidence,evidence_stance
0,Colloidal silver is effective for any infection,"Under the ""News"" tab of your website, your art...",insufficient-supports
1,"Claims ""Dumber and Dumber"" actor Jim Carrey sa...",He’s one of my favourite actors of all time. I...,insufficient-neutral
2,Claims that Barbara Walters wrote long stateme...,FACT CHECK: Did Barbara Walters Author This St...,insufficient-refutes
3,Agreement on real time information sharing wit...,The agreement between Switzerland and the Euro...,insufficient-supports
4,There are only DUP members (who are/were membe...,The Democratic Unionist Party (DUP) is a union...,insufficient-neutral

In [19]:
resplit_df['evidence_stance'].value_counts()

evidence_stance
refutes                       966
insufficient-neutral          728
supports                      622
insufficient-supports         461
insufficient-refutes          348
insufficient-contradictory    269
Name: count, dtype: int64

In [20]:
def label_rework(x):
    if x == 'refutes' or x == 'insufficient-refutes':
        return 'False'
    elif x == 'supports' or x == 'insufficient-supports':
        return 'True'
    else:
        return 'Nuanced'
    
resplit_df['evidence_stance'] = resplit_df['evidence_stance'].apply(label_rework)
resplit_df.head()

,claim,evidence,evidence_stance
0,Colloidal silver is effective for any infection,"Under the ""News"" tab of your website, your art...",True
1,"Claims ""Dumber and Dumber"" actor Jim Carrey sa...",He’s one of my favourite actors of all time. I...,Nuanced
2,Claims that Barbara Walters wrote long stateme...,FACT CHECK: Did Barbara Walters Author This St...,False
3,Agreement on real time information sharing wit...,The agreement between Switzerland and the Euro...,True
4,There are only DUP members (who are/were membe...,The Democratic Unionist Party (DUP) is a union...,Nuanced

In [21]:
resplit_df.columns = ['claim', 'documents', 'label']
resplit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3394 entries, 0 to 3393
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   claim      3394 non-null   object
 1   documents  3394 non-null   object
 2   label      3394 non-null   object
dtypes: object(3)
memory usage: 79.7+ KB

In [ ]:
claims_df = pd.concat([claims_df, resplit_df])
claims_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8330 entries, 0 to 3393
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   documents  8330 non-null   object
 1   claim      8330 non-null   object
 2   label      8330 non-null   object
dtypes: object(3)
memory usage: 260.3+ KB

:

8k rows, though more are possible with the full dataset of the tingchih/Multi_News_fact_checking_claims dataset. For finetuning, most likely that dataset will be used, as it contains more data.